// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IRecipeNutritionDetails {
  item: Item;
  tags: string[];
  type: string;
}

export interface Item {
  country_code:         string;
  deleted:              boolean;
  description:          string;
  id:                   number;
  nutritional_contents: NutritionalContents;
  public:               boolean;
  serving_sizes:        ServingSize[];
  type:                 string;
  user_id:              string;
  verified:             boolean;
  version:              string;
}

export interface NutritionalContents {
  calcium:             number;
  carbohydrates:       number;
  cholesterol:         number;
  energy:              Energy;
  fat:                 number;
  fiber:               number;
  iron:                number;
  monounsaturated_fat: number;
  polyunsaturated_fat: number;
  potassium:           number;
  protein:             number;
  saturated_fat:       number;
  sodium:              number;
  sugar:               number;
  trans_fat:           number;
  vitamin_a:           number;
  vitamin_c:           number;
  vitamin_d:           number;
}

export interface Energy {
  unit:  string;
  value: number;
}

export interface ServingSize {
  id:                   string;
  index:                number;
  nutrition_multiplier: number;
  unit:                 string;
  value:                number;
}
